version: '3'
services:
  mysql:
    build: ./mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_DATABASE=suscan
      - MYSQL_ROOT_PASSWORD=woaini520
    ports:
      - "3305:3306"
    restart: always
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
    ]
  server:
    container_name: 'server'
    build: .
    ports:
      - "18000:18000"
    links:
      - mysql:mysql
    depends_on:
      - mysql
    restart: always
    environment:
      - TZ=Asia/Shanghai
