Server:
  RunMode: debug
  HttpPort: 18000
  ReadTimeout: 60
  WriteTimeout: 60
App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  JwtSecret: fas65fd4541e352231a#D12
Database:
  DBType: mysql
  UserName: root
  Password: woaini520
  Host: 127.0.0.1:3306
  DBName: suscan
  TablePrefix:
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30